FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN set -ex && mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install gensim==3.8.2
RUN pip install -r requirements.txt
RUN python -c "import nltk; nltk.download('punkt')"
COPY . /code/