version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2020
  nginxservice:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile_django
    command: >
      bash -c "python manage.py migrate --settings=SFIAGenerator.settings.docker
      && python manage.py collectstatic --noinput --settings=SFIAGenerator.settings.docker
      && gunicorn SFIAGenerator.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  .: