# Generated by Django 3.0.4 on 2020-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_auto_20200324_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
