# Generated by Django 3.0.4 on 2020-03-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0004_auto_20200324_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
